# Generated by Django 5.1.7 on 2025-04-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transection_id',
            new_name='transaction_id',
        ),
    ]
