# Generated by Django 5.1.7 on 2025-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdfood',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
