# Generated by Django 5.1.7 on 2025-04-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdfood_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
