# Generated by Django 5.1.7 on 2025-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_parcentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Percentage (%)'),
        ),
    ]
